CREATE TABLE IF NOT EXISTS pedido (
  id BIGINT PRIMARY KEY,
  criado_em TIMESTAMP WITH TIME ZONE NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'RECEBIDO'
);

CREATE TABLE IF NOT EXISTS item_pedido (
  id BIGSERIAL PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
  produto_id BIGINT NOT NULL,
  quantidade BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS evento_pedido (
  event_id CHAR(36) PRIMARY KEY,
  pedido_id BIGINT NOT NULL REFERENCES pedido(id) ON DELETE CASCADE,
  tipo_evento VARCHAR(50) NOT NULL,
  ocorrido_em TIMESTAMP WITH TIME ZONE NOT NULL,
  publicado BOOLEAN NOT NULL DEFAULT FALSE
);